version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        depends_on:
          postgres:
            condition: service_healthy
        environment:
          SERVER_PORT: ${SERVER_PORT}

    postgres:
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "user"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4:4.18
      restart: always
      ports:
        - "${PGADMIN_PORT}:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:

