version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        env_file: .env
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        depends_on:
          postgres:
            condition: service_healthy
        env_file: .env

    postgres:
      container_name: postgres
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      env_file: .env
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4:4.18
      restart: always
      ports:
        - "${PGADMIN_PORT}:80"
      env_file: .env
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:

